"use client";

import { useState } from "react";
import { Printer, Loader2 } from "lucide-react";
import { jsPDF } from "jspdf";

interface Ingredient {
  item: string;
  amount: string;
  unit: string;
}

interface ShoppingListPDFProps {
  recipeTitle: string;
  ingredients: Ingredient[];
  servings: number;
}

export default function ShoppingListPDF({
  recipeTitle,
  ingredients,
  servings,
}: ShoppingListPDFProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = async () => {
    setIsGenerating(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      let y = 20;

      const today = new Date().toLocaleDateString("en-US", {
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      });

      // Header
      doc.setFontSize(24);
      doc.setTextColor(31, 41, 55); // gray-800
      doc.text("Shopping List", margin, y);
      y += 10;

      doc.setFontSize(10);
      doc.setTextColor(107, 114, 128); // gray-500
      doc.text(today, margin, y);
      y += 8;

      doc.setFontSize(12);
      doc.setTextColor(236, 72, 153); // pink-500
      doc.text(`For: ${recipeTitle} (${servings} servings)`, margin, y);
      y += 5;

      // Pink line under header
      doc.setDrawColor(236, 72, 153);
      doc.setLineWidth(0.5);
      doc.line(margin, y, pageWidth - margin, y);
      y += 15;

      // Ingredients
      doc.setFontSize(11);
      ingredients.forEach((ingredient) => {
        // Check if we need a new page
        if (y > 270) {
          doc.addPage();
          y = 20;
        }

        // Checkbox
        doc.setDrawColor(156, 163, 175); // gray-400
        doc.setLineWidth(0.3);
        doc.rect(margin, y - 4, 5, 5);

        // Amount + unit in pink
        doc.setTextColor(236, 72, 153); // pink-500
        doc.setFont("helvetica", "bold");
        const amountText = `${ingredient.amount} ${ingredient.unit}`;
        doc.text(amountText, margin + 8, y);

        // Item name in gray
        const amountWidth = doc.getTextWidth(amountText);
        doc.setTextColor(55, 65, 81); // gray-700
        doc.setFont("helvetica", "normal");
        doc.text(` ${ingredient.item}`, margin + 8 + amountWidth, y);

        // Separator line
        y += 3;
        doc.setDrawColor(229, 231, 235); // gray-200
        doc.setLineWidth(0.1);
        doc.line(margin, y, pageWidth - margin, y);
        y += 8;
      });

      // Tips box
      y += 5;
      if (y > 240) {
        doc.addPage();
        y = 20;
      }

      // Yellow background for tips
      doc.setFillColor(254, 243, 199); // amber-50
      doc.setDrawColor(252, 211, 77); // amber-300
      doc.roundedRect(margin, y, pageWidth - margin * 2, 30, 3, 3, "FD");

      y += 8;
      doc.setFontSize(11);
      doc.setTextColor(146, 64, 14); // amber-900
      doc.setFont("helvetica", "bold");
      doc.text("Shopping Tips", margin + 5, y);

      y += 6;
      doc.setFontSize(9);
      doc.setTextColor(161, 98, 7); // amber-700
      doc.setFont("helvetica", "normal");
      const tipText =
        "Check your pantry before shopping - you might already have some of these items! Fresh ingredients are always best for optimal flavor.";
      const splitTip = doc.splitTextToSize(tipText, pageWidth - margin * 2 - 10);
      doc.text(splitTip, margin + 5, y);

      // Footer
      y = 280;
      doc.setDrawColor(229, 231, 235);
      doc.setLineWidth(0.1);
      doc.line(margin, y, pageWidth - margin, y);
      y += 5;
      doc.setFontSize(9);
      doc.setTextColor(156, 163, 175); // gray-400
      doc.text("Generated by Sweet Recipes Hub", pageWidth / 2, y, {
        align: "center",
      });

      // Save the PDF
      const fileName = `shopping-list-${recipeTitle
        .toLowerCase()
        .replace(/\s+/g, "-")}.pdf`;
      doc.save(fileName);
    } catch (error) {
      console.error("Error generating PDF:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={generatePDF}
      disabled={isGenerating}
      className="w-full py-2 text-sm text-primary-600 hover:text-primary-700 font-medium flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
    >
      {isGenerating ? (
        <>
          <Loader2 size={16} className="animate-spin" />
          Generating PDF...
        </>
      ) : (
        <>
          <Printer size={16} />
          Print Shopping List
        </>
      )}
    </button>
  );
}
